
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  username: yash1234
  password: 12345
  host: localhost
  database: Dashboard_development


test:
  <<: *default
  encoding: unicode
  username: yash1234
  password: 12345
  database: Dashboard_test
  host: localhost


production:
  <<: *default
  database: DashBoard_production
  username: yash1234
  password: 12345