
default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  adapter: postgresql
  encoding: unicode
  username: harry
  password: harry123
  host: localhost
  database: Dashboard_development


test:
  <<: *default
  adapter: postgresql
  encoding: unicode
  username: harry
  password: harry123
  database: Dashboard_test


production:
  <<: *default
  database: DashBoard_production
